/* THE MANUSCRIPTS, AND WHAT KEEPING THEM COMES TO.
   =================================================================
   Five books stand in the world. Each one carries a subject out of Sahih
   al-Bukhari, and each reading inside it is a report with its chain, its words
   and a plain English reading underneath.

   THE TEXT IS NOT WRITTEN HERE. assets/rawda.json is generated by the same
   pipeline that builds the reading pages - it is fetched out of the parsed
   Sultaniyya by hadith number, and a number that is not in the book, or a matn
   with a character lost in the scrape, stops that build rather than shipping.
   So there is exactly one copy of this text and the game is not it. If a
   reading changes, it changes there and is exported again.

   What a player does with them:
     find    - walk up to a book and it offers itself
     read    - one reading at a time, kept where she left off
     keep    - a reading she has read is hers; the book fills up as she goes
     seal    - a book read to the end is sealed, and the seal is on her page

   Everything she has done is in one object, saved as one key. A save that is
   spread over a dozen keys is a save that goes out of step with itself. */
(function () {
  'use strict';
  var W = window.W = window.W || {};

  var SAVE = 'amirat.rawda.v1';

  /* WHERE THE BOOKS STAND.
     Each is placed against something already in the world, so a book is
     somewhere a person would keep one and not on a patch of open ground.
     `at` is resolved at build time against the places the world reports. */
  var PLACES = [
    { slug: 'prophets', at: 'library',  ar: 'قِصَصُ الأَنْبِيَاء' },
    { slug: 'creation', at: 'mosque',   ar: 'بَدْءُ الخَلْق' },
    { slug: 'angels',   at: 'minaret',  ar: 'ذِكْرُ المَلَائِكَة' },
    { slug: 'jannah',   at: 'well',     ar: 'صِفَةُ الجَنَّة' },
    { slug: 'seerah',   at: 'gate',     ar: 'السِّيرَة' }
  ];

  /* ------------------------------------------------------------- the save */
  function blank() {
    return { name: '', read: {}, sealed: {}, opened: 0, since: 0 };
  }

  var P = blank();

  function loadSave() {
    try {
      var raw = localStorage.getItem(SAVE);
      if (raw) {
        var j = JSON.parse(raw);
        if (j && typeof j === 'object') {
          P = { name: j.name || '', read: j.read || {}, sealed: j.sealed || {},
                opened: j.opened || 0, since: j.since || 0 };
        }
      }
    } catch (e) { P = blank(); }
    if (!P.since) P.since = 0;
    return P;
  }

  function save() {
    try { localStorage.setItem(SAVE, JSON.stringify(P)); } catch (e) {}
  }

  W.profile = function () { return P; };
  W.profileSave = save;
  W.profileReset = function () { P = blank(); save(); };

  /* ------------------------------------------------------------ the books */
  var BOOKS = [];          /* one per manuscript, once rawda.json has landed */
  var DATA = null;

  W.RAWDA_READY = false;

  function readKey(slug, i) { return slug + ':' + i; }

  W.hasRead = function (slug, i) { return !!P.read[readKey(slug, i)]; };

  W.markRead = function (slug, i) {
    var k = readKey(slug, i);
    if (P.read[k]) return false;
    P.read[k] = 1;
    P.opened++;
    /* a book read to the end is sealed, once */
    var b = W.book(slug);
    if (b && !P.sealed[slug] && W.bookRead(slug) >= b.items.length) {
      P.sealed[slug] = 1;
      if (W.onSeal) W.onSeal(b);
    }
    save();
    return true;
  };

  W.book = function (slug) {
    if (!DATA) return null;
    for (var i = 0; i < DATA.topics.length; i++) {
      if (DATA.topics[i].slug === slug) return DATA.topics[i];
    }
    return null;
  };

  W.books = function () { return DATA ? DATA.topics : []; };

  W.bookRead = function (slug) {
    var b = W.book(slug);
    if (!b) return 0;
    var n = 0;
    for (var i = 0; i < b.items.length; i++) if (W.hasRead(slug, i)) n++;
    return n;
  };

  W.totalReadings = function () {
    var n = 0, t = W.books();
    for (var i = 0; i < t.length; i++) n += t[i].items.length;
    return n;
  };

  /* --------------------------------------------------------- what she is
     THE LEVEL IS THE READING, NOT THE WALKING. There is nothing to grind
     here: the only thing that moves it is having read something, and every
     reading counts once. The bands are named rather than numbered, because a
     number would invite her to ask what the next number is worth. */
  var BANDS = [
    { at: 0,  ar: 'مُبْتَدِئَة', en: 'Beginning' },
    { at: 3,  ar: 'طَالِبَة', en: 'Seeking' },
    { at: 10, ar: 'قَارِئَة', en: 'Reading' },
    { at: 22, ar: 'حَافِظَة', en: 'Keeping' },
    { at: 38, ar: 'رَاوِيَة', en: 'Relating' },
    { at: 56, ar: 'عَالِمَة', en: 'Learned' },
    { at: 70, ar: 'أَمِيرَةُ العُلُوم', en: 'Amiratu al-ʿUlum' }
  ];

  W.band = function () {
    var n = P.opened, cur = BANDS[0], next = null;
    for (var i = 0; i < BANDS.length; i++) {
      if (n >= BANDS[i].at) cur = BANDS[i];
      else { next = BANDS[i]; break; }
    }
    return { now: cur, next: next, read: n, total: W.totalReadings() };
  };

  W.BANDS = BANDS;

  /* ------------------------------------------------------- standing them up
     A book is a real object on a real stand, and the stand is put where the
     world says that place is. Nothing is placed at a guessed coordinate: if
     the world has not built that place, the book is not stood up at all and
     says so, rather than being left floating in a field. */
  function spotFor(kind) {
    var T = W.TOWN || { x: 0, y: 7, z: 0 };
    if (kind === 'mosque' && W.MOSQUE) {
      return { x: W.MOSQUE.x + 6.5, y: W.MOSQUE.y, z: W.MOSQUE.z + 3.0 };
    }
    if (kind === 'library' && W.LIBRARY) {
      return { x: W.LIBRARY.x, y: W.LIBRARY.y, z: W.LIBRARY.z + 3.4 };
    }
    if (kind === 'minaret' && W.MOSQUE) {
      return { x: W.MOSQUE.x - 13.0, y: W.MOSQUE.y, z: W.MOSQUE.z + 12.0 };
    }
    /* The bustan is a real garden, but it stands two hundred metres outside
       the walls, which is a walk and not a discovery. The open places inside
       the town are published by the world with a real ground height, so the
       last two books go where people already gather: the well in the middle,
       and the square just inside the gate. */
    if (W.SQUARES && W.SQUARES.length) {
      var s = null;
      if (kind === 'well') s = W.SQUARES[0];
      else if (kind === 'gate') s = W.SQUARES[4] || W.SQUARES[1];
      if (s) return { x: s.x + 2.4, y: s.y, z: s.z + 2.4 };
    }
    return null;
  }

  W.standBooks = function () {
    if (!DATA || !W.placeBook) return 0;
    BOOKS.length = 0;
    var made = 0, lost = [];
    for (var i = 0; i < PLACES.length; i++) {
      var pl = PLACES[i];
      var b = W.book(pl.slug);
      if (!b) continue;
      var at = spotFor(pl.at);
      if (!at) { lost.push(pl.at); continue; }
      var g = W.placeBook(pl.slug, at.x, at.y, at.z);
      if (!g) { lost.push(pl.at); continue; }
      /* TAKE THE POSITION OFF THE THING THAT WAS BUILT, not off what was
         asked for. placeBook moves a book that would have stood inside
         something, and a reach test against the spot we requested would then
         be testing a place the book is not. */
      BOOKS.push({ slug: pl.slug, ar: pl.ar,
                   x: g.position.x, y: g.position.y, z: g.position.z, g: g });
      made++;
    }
    if (lost.length && W.diag) {
      W.diag('no place in the world for: ' + lost.join(', '));
    }
    return made;
  };

  /* which book is within reach, if any */
  W.bookNear = function (p, reach) {
    var best = null, bd = reach || 3.2;
    for (var i = 0; i < BOOKS.length; i++) {
      var b = BOOKS[i];
      var d = Math.hypot(p.x - b.x, p.z - b.z);
      if (d < bd && Math.abs(p.y - b.y) < 4.0) { bd = d; best = b; }
    }
    return best;
  };

  W.BOOKS = BOOKS;

  /* THE BOOKS CANNOT BE STOOD UP UNTIL BOTH THINGS HAVE HAPPENED.
     The world has to have been built - a book is placed against the library or
     the mosque, and those do not exist until the models have landed - and the
     readings have to have arrived, because a book with no readings in it is a
     lectern with nothing on it. The two are fetched in parallel and either may
     finish first, so this waits for both and then does it once. */
  var stood = false;
  W.standBooksWhenReady = function () {
    if (stood) return;
    if (!W.RAWDA_READY || !W.MODELS_IN || !W.placeBook) {
      setTimeout(W.standBooksWhenReady, 400);
      return;
    }
    stood = true;
    var n = W.standBooks();
    if (W.diag) W.diag('the readings: ' + n + ' books stood up');
    if (W.uiRefresh) W.uiRefresh();
  };

  /* ---------------------------------------------------------------- boot */
  loadSave();

  W.loadRawda = function () {
    var v = window.__BUILD || '';
    return fetch('assets/rawda.json?v=' + v)
      .then(function (r) { return r.json(); })
      .then(function (j) {
        DATA = j;
        W.RAWDA_READY = true;
        if (!P.since) { P.since = Date.now(); save(); }
        return j;
      })
      .catch(function (e) {
        if (W.diag) W.diag('the readings did not load: ' + e.message);
        return null;
      });
  };
})();
